server:
  port: 8080

spring:
  datasource:
    username: lq0019999
    password: aaaaaa
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver